// {Common Name Latin Name}
var plants = [
{"common":" ", "latin":" "},
{"common":"Abelia Glossy", "latin":"Abelia"},
{"common":"Alder", "latin":"Alnus"},
{"common":"Almond", "latin":"Prunus"},
{"common":"Andromeda", "latin":"Pieris"},
{"common":"Apple Crabapple", "latin":"Malus"},
{"common":"Arborvitae", "latin":"Thuja"},
{"common":"Aster Stoke’s", "latin":"Stokesia"},
{"common":"Azalea", "latin":"Azalea"},
{"common":"Baby’s Breath", "latin":"Gypsophila"},
{"common":"Balloon Flower", "latin":"Platycodon"},
{"common":"Barberry", "latin":"Berberis"},
{"common":"Barrenwort", "latin":"Epimedium"},
{"common":"Bayberry", "latin":"Myrica"},
{"common":"Bearberry", "latin":"Arcostaphylos uva-ursi"},
{"common":"Beard Tongue", "latin":"Penstemon"},
{"common":"Beauty Bush", "latin":"Kolkwitzia amabilis"},
{"common":"Bee Balm", "latin":"Monarda"},
{"common":"Beech", "latin":"Fagus sylvatica"},
{"common":"Bell Flower", "latin":"Campanula"},
{"common":"Bergenia Heartleaf", "latin":"Bergenia"},
{"common":"Beautyberry", "latin":"Callicarpa"},
{"common":"Birch", "latin":"Betula"},
{"common":"Black-Eyed Susan", "latin":"Rudbeckia"},
{"common":"Blanket Flower", "latin":"Gaillardia"},
{"common":"Blueberry", "latin":"Vaccinium"},
{"common":"Blue Mist", "latin":"Caryopteris"},
{"common":"Blue Star", "latin":"Amsonia"},
{"common":"Boxwood", "latin":"Buxus"},
{"common":"Bugbane", "latin":"Cimicifuga"},
{"common":"Bugleweed", "latin":"Ajuga"},
{"common":"Butterfly Bush", "latin":"Buddleia"},
{"common":"Butterfly Weed", "latin":"Asclepias"},
{"common":"Button Bush", "latin":"Cephalanthus occidentalis"},
{"common":"Candytuft", "latin":"Iberis"},
{"common":"Cardinal Flower", "latin":"Lobelia"},
{"common":"Carnations Hardy", "latin":"Dianthus"},
{"common":"Cedar", "latin":"Cedrus"},
{"common":"Cedar Eastern Red", "latin":"Juniperus virginiana"},
{"common":"Cedar Japanese", "latin":"Cryptomeria japonica"},
{"common":"Cherry", "latin":"Prunus"},
{"common":"Chokeberry", "latin":"Aronia"},
{"common":"Chrysanthemum Hardy", "latin":"Dendranthemum"},
{"common":"Cinquefoil Bush", "latin":"Potentilla fruiticosa"},
{"common":"Clematis", "latin":"Clematis"},
{"common":"Columbine", "latin":"Aquilegia"},
{"common":"Cone Flower", "latin":"Echinacea"},
{"common":"Cornflower", "latin":"Centaurea"},
{"common":"Cotoneaster", "latin":"Cotoneaster"},
{"common":"Cranesbill", "latin":"Geranium"},
{"common":"Cypress Bald", "latin":"Taxodium distichum"},
{"common":"Cypress Russian", "latin":"Microbiota decussata"},
{"common":"Daisy Montauk", "latin":"Nipponantheum"},
{"common":"Daisy Shasta", "latin":"Leucanthemum"},
{"common":"Daylily", "latin":"Hemerocallis"},
{"common":"Deutzia", "latin":"Deutzia"},
{"common":"Dogwood", "latin":"Cornus"},
{"common":"Elderberry", "latin":"Sambucus"},
{"common":"Elm", "latin":"Ulmus"},
{"common":"Enkianthus Redvein", "latin":"Enkianthus"},
{"common":"Euonymous ", "latin":"Euonymous"},
{"common":"Falsecypress", "latin":"Chamaecyparis"},
{"common":"False Indigo", "latin":"Baptisia"},
{"common":"Fern Sweet", "latin":"Comptonia peregrina"},
{"common":"Fir", "latin":"Abies"},
{"common":"Fir Douglas", "latin":"Pseudotsuga menziesii"},
{"common":"Forget-Me-Not Blue", "latin":"Brunnera"},
{"common":"Forsythia", "latin":"Forsythia"},
{"common":"Fothergilla", "latin":"Fothergilla"},
{"common":"Foxglove", "latin":"Digitalis"},
{"common":"Fringe Tree", "latin":"Chionanthus"},
{"common":"Germander", "latin":"Teucreum"},
{"common":"Goatsbeard", "latin":"Aruncus"},
{"common":"Golden Chain Tree", "latin":"Laburnum"},
{"common":"Golden Ray", "latin":"Ligularia"},
{"common":"Hawthorne", "latin":"Crataegus"},
{"common":"Hemlock Canadian", "latin":"Tsuga canadensis"},
{"common":"Hens and Chicks", "latin":"Sempervivum"},
{"common":"Holly", "latin":"Ilex"},
{"common":"Honeylocust", "latin":"Gleditsia"},
{"common":"Honeysuckle", "latin":"Lonicera"},
{"common":"Honeysuckle Bush", "latin":"Diervilla"},
{"common":"Hornbeam European", "latin":"Carpinus betulus"},
{"common":"Horsechestnut (Buckeye)", "latin":"Aesculus"},
{"common":"Hosta (Plantain Lilies)", "latin":"Hosta"},
{"common":"Hydrangea", "latin":"Hydrangea"},
{"common":"Hydrangea Vine Japanese", "latin":"Schizophragma hydrangeoides"},
{"common":"Hyssop", "latin":"Agastache"},
{"common":"Inkberry", "latin":"Ilex glabra"},
{"common":"Iris", "latin":"Iris"},
{"common":"Ivy Boston", "latin":"Parthenocissus tricuspidata"},
{"common":"Ivy Hardy English", "latin":"Hedera helix"},
{"common":"Jacob’s Ladder", "latin":"Polemonium"},
{"common":"Joe Pye Weed", "latin":"Eupatorium"},
{"common":"Juniper", "latin":"Juniperus"},
{"common":"Katsura", "latin":"Cercidiphyllum japonicum"},
{"common":"Kerria Japanese", "latin":"Kerria japonica"},
{"common":"Lady’s Mantle", "latin":"Alchemilla"},
{"common":"Lamb’s Ears", "latin":"Stachys"},
{"common":"Larkspur", "latin":"Delphinium"},
{"common":"Lavender", "latin":"Lavandula"},
{"common":"Leucothoe", "latin":"Leucothoe"},
{"common":"Lilac", "latin":"Syringa"},
{"common":"Lily of the Valley", "latin":"Convallaria"},
{"common":"Lily Turf", "latin":"Liriope"},
{"common":"Linden Little Leaf", "latin":"Tilia cordata"},
{"common":"London Plane", "latin":"Platanus acerifolia ‘Bloodgood’"},
{"common":"Lungwort", "latin":"Pulmonaria"},
{"common":"Magnolia", "latin":"Magnolia"},
{"common":"Maple", "latin":"Acer"},
{"common":"Meadow Rue", "latin":"Thalictrum"},
{"common":"Meadowsweet", "latin":"Filipendula"},
{"common":"Mockorange", "latin":"Philadelphus"},
{"common":"Monkshood", "latin":"Aconitum"},
{"common":"Mountain Laurel", "latin":"Kalmia"},
{"common":"Mountain Pinks", "latin":"Phlox subulata"},
{"common":"Myrtle", "latin":"Vinca Minor"},
{"common":"Nettle Spotted Dead", "latin":"Lamium"},
{"common":"Ninebark", "latin":"Physocarpus"},
{"common":"Oak", "latin":"Quercus"},
{"common":"Obedient Plant", "latin":"Physostegia"},
{"common":"Pachysandra (Japanese Spurge)", "latin":"Pachysandra"},
{"common":"Pea Weeping", "latin":"Caragana arborescens pendula"},
{"common":"Pear", "latin":"Pyrus"},
{"common":"Peony", "latin":"Paeonia"},
{"common":"Phlox", "latin":"Phlox"},
{"common":"Pincushion Flower", "latin":"Scabiosa"},
{"common":"Pine", "latin":"Pinus"},
{"common":"Pine Umbrella", "latin":"Sciadopitys verticillata"},
{"common":"Plum", "latin":"Prunus"},
{"common":"Plumbago (Leadwort)", "latin":"Ceratostigma"},
{"common":"Poppy Oriental", "latin":"Papaver"},
{"common":"Privet", "latin":"Ligustrum"},
{"common":"Quince Flowering", "latin":"Chaenomeles"},
{"common":"Redbud", "latin":"Cercis canadensis"},
{"common":"Red Bud Hazel", "latin":"Disanthus cercidifolius"},
{"common":"Red Hot Poker", "latin":"Kniphofia"},
{"common":"Redwood Dawn", "latin":"Metasequoia glyptostroboides"},
{"common":"Rhododendron", "latin":"Rhododendron"},
{"common":"Rodger’s Flower", "latin":"Rodgersia"},
{"common":"Rose", "latin":"Rosa"},
{"common":"Rose of Sharon", "latin":"Hibiscus"},
{"common":"Rose Lenten", "latin":"Helleborus"},
{"common":"Sage Meadow", "latin":"Salvia"},
{"common":"Sage Russian", "latin":"Perovskia"},
{"common":"Sedge", "latin":"Carex"},
{"common":"Seven-son Flower", "latin":"Heptacodium miconioides"},
{"common":"Serviceberry (Shadblow)", "latin":"Amelanchier"},
{"common":"Skimmia Japanese", "latin":"Skimmia"},
{"common":"Smoke Bush Purple", "latin":"Cotinus coggygria"},
{"common":"Sneezeweed", "latin":"Helenium"},
{"common":"Snow in Summer", "latin":"Cerastium"},
{"common":"Solomon’s Seal", "latin":"Polygonatum"},
{"common":"Sourwood", "latin":"Oxydendrum arboreum"},
{"common":"Speedwell", "latin":"Veronica"},
{"common":"Spice Bush", "latin":"Lindera benzoin"},
{"common":"Spirea", "latin":"Spiraea"},
{"common":"Spirea Ash Leaf", "latin":"Sorbaria sorbifolia"},
{"common":"Spirea False", "latin":"Astilbe"},
{"common":"Spruce", "latin":"Picea"},
{"common":"Spurge Cushion", "latin":"Euphorbia"},
{"common":"St. Johnswort", "latin":"Hypericum"},
{"common":"Stephanandra", "latin":"Stephanandra"},
{"common":"Stewartia", "latin":"Stewartia"},
{"common":"Stonecrop", "latin":"Sedum"},
{"common":"Styrax", "latin":"Styrax"},
{"common":"Sumac", "latin":"Rhus"},
{"common":"Summersweet", "latin":"Clethra"},
{"common":"Sunflower False", "latin":"Heliopsis"},
{"common":"Sweet Flag", "latin":"Acorus"},
{"common":"Sweetbox", "latin":"Sarcococca hookeriana"},
{"common":"Sweetgum", "latin":"Liquidambar styraciflua"},
{"common":"Sweetshrub", "latin":"Calycanthus floridus"},
{"common":"Sweetspire Virginia", "latin":"Itea virginicus"},
{"common":"Symphoricarpos", "latin":"Symphoricarpos"},
{"common":"Thyme Creeping", "latin":"Thymus"},
{"common":"Tickseed", "latin":"Coreopsis"},
{"common":"Toad Lily", "latin":"Tricyrtis"},
{"common":"Trumpet Vine", "latin":"Campsis"},
{"common":"Tupelo (Sour Gum)", "latin":"Nyssa sylvatica"},
{"common":"Turtlehead", "latin":"Chelone"},
{"common":"Viburnum", "latin":"Viburnum"},
{"common":"Walking Stick Harry Lauder’s", "latin":"Corylus avellana"},
{"common":"Wand Flower", "latin":"Gaura"},
{"common":"Weigela", "latin":"Weigela"},
{"common":"Willow", "latin":"Salix"},
{"common":"Windflower", "latin":"Anemone"},
{"common":"Winterberry", "latin":"Ilex verticillata"},
{"common":"Wintergreen", "latin":"Gaultheria procumbens"},
{"common":"Winterhazel", "latin":"Corylopsis"},
{"common":"Wisteria", "latin":"Wisteria"},
{"common":"Witchhazel", "latin":"Hamamelis"},
{"common":"Woodruff Sweet", "latin":"Galium"},
{"common":"Wormwood", "latin":"Artemisia"},
{"common":"Yarrow", "latin":"Achillea"},
{"common":"Yew", "latin":"Taxus"},
{"common":"Zelkova", "latin":"Zelkova"}]