var subs = [
{"start":0.02 , "text":"Imagine, if you will, that something has gone terribly wrong", "cap":true, "font":1},
{"start":0.07 , "text":"All that's happening is that numbers are going up", "cap":true, "font":2},
{"start":0.10 , "text":"It is a deeply repugnant traffic that we need to stop", "cap":false, "font":1},
{"start":0.14 , "text":"Stop! You've no idea!", "cap":true, "font":2},
{"start":0.16 , "text":"Who are these people that are coming here", "cap":false, "font":1},
{"start":0.18 , "text":"Do we know their backgrounds?", "cap":false, "font":1},
{"start":0.19 , "text":"No, we don't", "cap":false, "font":1},
{"start":0.20 , "text":"They're after us. They're after the place", "cap":false, "font":1},
{"start":0.22 , "text":"They must be detained until they can be deported.", "cap":false, "font":1},
{"start":0.25 , "text":"What the hell are they?", "cap":false, "font":1},
{"start":0.26 , "text":"Are they Oasis?", "cap":false, "font":1},
{"start":0.27 , "text":"Are they Dius?", "cap":false, "font":1},
{"start":0.28 , "text":"Are they Taliban?", "cap":false, "font":1},
{"start":0.29 , "text":"Are they Somalian pirates?", "cap":false, "font":1},
{"start":0.31 , "text":"This situation must be controlled before it's too late", "cap":true, "font":2},
{"start":0.34 , "text":"They are multiplying too rapidly!", "cap":true, "font":2},
{"start":0.36 , "text":"These are invaders. You should be protecting us, not them", "cap":false, "font":1},
{"start":0.39 , "text":"Are these people alive or dead?", "cap":false, "font":1},
{"start":0.41 , "text":"We don't know", "cap":false, "font":1},
{"start":0.42 , "text":"As long as the weather's okay,they're going to keep coming", "cap":false, "font":1},
{"start":0.44 , "text":"There are too many of them out there", "cap":false, "font":1},
{"start":0.45 , "text":"The political elites at the moment doing absolutely nothing, and it is an invasion.", "cap":false, "font":1},
{"start":0.49 , "text":"We are being invaded.", "cap":false, "font":1},
{"start":0.50 , "text":"Just keep coming", "cap":false, "font":1},
{"start":0.52 , "text":"We're in the minority now. Something like 400,000 to one, by my calculations", "cap":false, "font":1},
{"start":0.55 , "text":"I saw one of those things take 30 hits and keep on coming.", "cap":false, "font":1},
{"start":0.59 , "text":"What are they?", "cap":false, "font":1},
{"start":0.61 , "text":"They are us! They are the same animal,  simply functioning less perfectly", "cap":false, "font":1},
{"start":0.65 , "text":"These creatures are nothing but pure, motorized instinct", "cap":false, "font":1},
{"start":0.71 , "text":"Deep, dark, primordial instinct", "cap":false, "font":1},
{"start":0.73 , "text":"And the sooner we start calling them illegal immigrants,then the sooner we can get this problem sorted", "cap":false, "font":1},
{"start":0.78 , "text":"We must not be lulled by the concept that these are our family members or our friends.", "cap":false, "font":1},
{"start":0.83 , "text":"They are not. They will not respond to such emotions", "cap":false, "font":1},
{"start":0.87 , "text":"I think we've got to look at all options", "cap":false, "font":1},
{"start":0.89 , "text":"We've got to remain rational, logical", "cap":false, "font":1},
{"start":0.92 , "text":"firm and fair", "cap":false, "font":1},
{"start":0.94 , "text":"We have spawned our own savagery", "cap":false, "font":1},
{"start":0.96 , "text":"Soon it will consume us all", "cap":false, "font":1},
{"start":0.99 , "text":"We want our country back. We want our country back", "cap":false, "font":1},
{"start":1.03 , "text":"They must be destroyed on site", "cap":false, "font":1},
{"start":1.07 , "text":"They're coming to get you, Barbara", "cap":false, "font":1},
{"start":1.11 , "text":"", "cap":false, "font":1}
];
